import { useEffect, useMemo, useState } from 'react'
import type { Board, Column, Priority, Task, WorkspaceSnapshot } from './domain'
import { kanbanService, ServiceError } from './services'

type Page = 'workspace' | 'about' | 'faq'
type Filters = { assigneeId: string; priority: string; labelId: string }

const emptyFilters: Filters = { assigneeId: '', priority: '', labelId: '' }

function formatDate(value?: string) { return value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : '' }
function getErrorMessage(error: unknown) { return error instanceof ServiceError ? error.message : 'Something went wrong. Please try again.' }

export default function App() {
  const [page, setPage] = useState<Page>('workspace')
  const [snapshot, setSnapshot] = useState<WorkspaceSnapshot>()
  const [selectedBoardId, setSelectedBoardId] = useState('b1')
  const [selectedTaskId, setSelectedTaskId] = useState<string>()
  const [filters, setFilters] = useState(emptyFilters)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')

  const refresh = async () => { setLoading(true); setError(''); try { const next = await kanbanService.getWorkspace(); setSnapshot(next); if (!next.boards[selectedBoardId]) setSelectedBoardId(next.team.boardIds[0]) } catch (error) { setError(getErrorMessage(error)) } finally { setLoading(false) } }
  useEffect(() => { void refresh() }, [])

  const mutate = async (operation: () => Promise<WorkspaceSnapshot>, success?: string) => { setError(''); try { const next = await operation(); setSnapshot(next); if (success) { setNotice(success); window.setTimeout(() => setNotice(''), 2400) } return next } catch (error) { setError(getErrorMessage(error)); return undefined } }

  if (loading || !snapshot) return <main className="loading-screen"><div className="logo-mark">◎</div><p>{loading ? 'Loading your workspace…' : error}</p>{error && <button onClick={() => void refresh()}>Retry</button>}</main>

  const currentUser = snapshot.users[snapshot.team.currentUserId]
  const unread = Object.values(snapshot.notifications).filter(notification => notification.recipientId === currentUser.id && !notification.read).length
  const board = snapshot.boards[selectedBoardId] ?? snapshot.boards[snapshot.team.boardIds[0]]
  const selectedTask = selectedTaskId ? snapshot.tasks[selectedTaskId] : undefined

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="logo-mark">◎</span><span>orbit</span><small>demo workspace</small></div>
      <div className="workspace-switcher"><span className="workspace-avatar">O</span><span><strong>{snapshot.team.name}</strong><small>Personal demo</small></span><span className="chevron">⌄</span></div>
      <nav aria-label="Primary navigation" className="primary-nav">
        <button aria-label="Workspace" className={page === 'workspace' ? 'nav-item active' : 'nav-item'} onClick={() => setPage('workspace')}>▦ <span>Workspace</span></button>
        <button aria-label="About" className={page === 'about' ? 'nav-item active' : 'nav-item'} onClick={() => setPage('about')}>✦ <span>About</span></button>
        <button aria-label="FAQ" className={page === 'faq' ? 'nav-item active' : 'nav-item'} onClick={() => setPage('faq')}>? <span>FAQ</span></button>
      </nav>
      <div className="sidebar-section"><div className="section-label">YOUR BOARDS <button aria-label="Create board" onClick={async () => { const name = window.prompt('Board name'); if (name) { const next = await mutate(() => kanbanService.createBoard(name), 'Board created'); if (next) setSelectedBoardId(next.team.boardIds[next.team.boardIds.length - 1]) } }}>+</button></div>{snapshot.team.boardIds.map(id => <button key={id} className={id === board.id ? 'board-link selected' : 'board-link'} onClick={() => { setSelectedBoardId(id); setPage('workspace') }}><span className="board-dot" />{snapshot.boards[id].name}</button>)}</div>
      <div className="sidebar-bottom"><button className="reset-button" onClick={async () => { if (window.confirm('Reset the demo workspace?')) { const next = await mutate(() => kanbanService.resetDemo(), 'Demo reset'); if (next) { setSelectedBoardId('b1'); setSelectedTaskId(undefined) } } }}>↻ Reset demo</button><div className="profile"><span className="avatar" style={{ background: currentUser.color }}>{currentUser.initials}</span><span><strong>{currentUser.name}</strong><small>{currentUser.role}</small></span><span className="more">•••</span></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{page === 'workspace' ? board.name : page === 'about' ? 'About Orbit' : 'Frequently asked questions'}</strong></div><div className="top-actions"><button className="icon-button" aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`} onClick={() => { const first = Object.values(snapshot.notifications).find(notification => notification.recipientId === currentUser.id); if (first) void mutate(() => kanbanService.markNotificationRead(first.id), 'Notification marked read') }}>♧{unread > 0 && <i>{unread}</i>}</button><button className="help-button" onClick={() => setPage('faq')}>Need help?</button></div></header>
      {notice && <div className="toast" role="status">✓ {notice}</div>}{error && <div className="error-banner" role="alert">{error}</div>}
      {page === 'workspace' ? <Workspace snapshot={snapshot} board={board} filters={filters} setFilters={setFilters} onMutate={mutate} onOpenTask={setSelectedTaskId} /> : <InfoPage page={page} onBack={() => setPage('workspace')} />}
    </main>
    {selectedTask && <TaskDialog snapshot={snapshot} task={selectedTask} onClose={() => setSelectedTaskId(undefined)} onMutate={mutate} />}
  </div>
}

function Workspace({ snapshot, board, filters, setFilters, onMutate, onOpenTask }: { snapshot: WorkspaceSnapshot; board: Board; filters: Filters; setFilters: (filters: Filters) => void; onMutate: (operation: () => Promise<WorkspaceSnapshot>, success?: string) => Promise<WorkspaceSnapshot | undefined>; onOpenTask: (taskId: string) => void }) {
  const columns = board.columnIds.map(id => snapshot.columns[id]).filter(Boolean)
  const visibleTasks = (columnId: string) => Object.values(snapshot.tasks).filter(task => task.columnId === columnId && !task.archived && (!filters.assigneeId || task.assigneeId === filters.assigneeId) && (!filters.priority || task.priority === filters.priority) && (!filters.labelId || task.labelIds.includes(filters.labelId))).sort((a, b) => a.order - b.order)
  const [draggedTaskId, setDraggedTaskId] = useState<string>()
  const addTask = async (columnId: string) => { const title = window.prompt('Task title'); if (title) await onMutate(() => kanbanService.createTask({ boardId: board.id, columnId, title }), 'Task added') }
  const manageColumn = async () => { const name = window.prompt('New column name'); if (name) await onMutate(() => kanbanService.addColumn(board.id, name), 'Column added') }
  return <section className="workspace-page"><div className="page-heading"><div><p className="eyebrow">{snapshot.team.name} / ACTIVE BOARD</p><h1>{board.name}</h1><p className="muted">A calm place for the work that moves your team forward.</p></div><div className="heading-actions"><button className="secondary-button" onClick={manageColumn}>＋ Manage columns</button><button className="primary-button" onClick={() => addTask(columns[0].id)}>＋ Add task</button></div></div>
    <div className="filter-bar"><span className="filter-label">FILTER BY</span><select aria-label="Filter by assignee" value={filters.assigneeId} onChange={event => setFilters({ ...filters, assigneeId: event.target.value })}><option value="">All people</option>{snapshot.team.memberIds.map(id => <option key={id} value={id}>{snapshot.users[id].name}</option>)}</select><select aria-label="Filter by priority" value={filters.priority} onChange={event => setFilters({ ...filters, priority: event.target.value })}><option value="">All priorities</option>{(['Low', 'Medium', 'High', 'Urgent'] as Priority[]).map(priority => <option key={priority}>{priority}</option>)}</select><select aria-label="Filter by label" value={filters.labelId} onChange={event => setFilters({ ...filters, labelId: event.target.value })}><option value="">All labels</option>{board.labelIds.map(id => <option key={id} value={id}>{snapshot.labels[id].name}</option>)}</select>{Object.values(filters).some(Boolean) && <button className="clear-filter" onClick={() => setFilters(emptyFilters)}>Clear filters</button>}</div>
    <div className="board-grid">{columns.map(column => { const tasks = visibleTasks(column.id); return <div className="column" key={column.id} onDragOver={event => event.preventDefault()} onDrop={async () => { if (draggedTaskId) await onMutate(() => kanbanService.moveTask({ taskId: draggedTaskId, destinationColumnId: column.id, destinationIndex: tasks.length }), 'Task moved'); setDraggedTaskId(undefined) }}><div className="column-header"><div><h2>{column.name}</h2><span>{tasks.length} {tasks.length === 1 ? 'task' : 'tasks'}</span></div><button aria-label={`Add task to ${column.name}`} onClick={() => addTask(column.id)}>＋</button></div><div className="task-list">{tasks.map(task => <TaskCard key={task.id} task={task} snapshot={snapshot} draggable onDragStart={() => setDraggedTaskId(task.id)} onOpen={() => onOpenTask(task.id)} onMutate={onMutate} />)}{tasks.length === 0 && <div className="empty-column">{Object.values(filters).some(Boolean) ? 'No matching tasks' : 'Nothing here yet'}<button onClick={() => addTask(column.id)}>Add a task</button></div>}</div></div> })}<button className="add-column" onClick={manageColumn}>＋ Add another column</button></div>
  </section>
}

function TaskCard({ task, snapshot, onOpen, onMutate, ...drag }: { task: Task; snapshot: WorkspaceSnapshot; onOpen: () => void; onMutate: (operation: () => Promise<WorkspaceSnapshot>, success?: string) => Promise<WorkspaceSnapshot | undefined>; draggable?: boolean; onDragStart?: () => void }) {
  const assignee = task.assigneeId ? snapshot.users[task.assigneeId] : undefined
  return <article className="task-card" draggable={drag.draggable} onDragStart={drag.onDragStart} tabIndex={0} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onOpen() } }} onClick={onOpen}><div className="task-card-top"><span className={`priority ${task.priority?.toLowerCase() ?? 'none'}`}>{task.priority ?? 'No priority'}</span>{task.blocked && <span className="blocked">Blocked</span>}<button className="card-menu" aria-label={`Actions for ${task.title}`} onClick={event => { event.stopPropagation(); onOpen() }}>•••</button></div><h3>{task.title}</h3><div className="card-meta">{assignee ? <span className="mini-person"><span className="avatar tiny" style={{ background: assignee.color }}>{assignee.initials}</span>{assignee.name.split(' ')[0]}</span> : <span className="mini-person unassigned">○ Unassigned</span>}{task.dueDate && <span>◷ {formatDate(task.dueDate)}</span>}{task.checklist.length > 0 && <span>☑ {task.checklist.filter(item => item.completed).length}/{task.checklist.length}</span>}</div>{task.labelIds.length > 0 && <div className="labels">{task.labelIds.map(labelId => <span key={labelId} className="label" style={{ borderColor: snapshot.labels[labelId]?.color, color: snapshot.labels[labelId]?.color }}>{snapshot.labels[labelId]?.name}</span>)}</div>}</article>
}

function TaskDialog({ snapshot, task, onClose, onMutate }: { snapshot: WorkspaceSnapshot; task: Task; onClose: () => void; onMutate: (operation: () => Promise<WorkspaceSnapshot>, success?: string) => Promise<WorkspaceSnapshot | undefined> }) {
  const [title, setTitle] = useState(task.title); const [description, setDescription] = useState(task.description); const [comment, setComment] = useState(''); const [checkText, setCheckText] = useState('')
  const update = async (input: Parameters<typeof kanbanService.updateTask>[1]) => { await onMutate(() => kanbanService.updateTask(task.id, input), 'Task updated') }
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="task-dialog" role="dialog" aria-modal="true" aria-labelledby="task-dialog-title"><button className="close-button" aria-label="Close task details" onClick={onClose}>×</button><div className="dialog-kicker">{task.archived ? 'ARCHIVED TASK' : 'TASK DETAILS'}</div><input id="task-dialog-title" className="task-title-input" value={title} onChange={event => setTitle(event.target.value)} onBlur={() => { if (title !== task.title) void update({ title }) }} /><textarea className="description-input" aria-label="Description" placeholder="Add a description…" value={description} onChange={event => setDescription(event.target.value)} onBlur={() => { if (description !== task.description) void update({ description }) }} />
    <div className="detail-grid"><label>Assignee<select value={task.assigneeId ?? ''} onChange={event => void update({ assigneeId: event.target.value || undefined })}><option value="">Unassigned</option>{snapshot.team.memberIds.map(id => <option key={id} value={id}>{snapshot.users[id].name}</option>)}</select></label><label>Priority<select value={task.priority ?? ''} onChange={event => void update({ priority: (event.target.value || undefined) as Priority | undefined })}><option value="">None</option>{(['Low', 'Medium', 'High', 'Urgent'] as Priority[]).map(priority => <option key={priority}>{priority}</option>)}</select></label><label>Due date<input type="date" value={task.dueDate ?? ''} onChange={event => void update({ dueDate: event.target.value })} /></label><label className="blocked-toggle"><input type="checkbox" checked={task.blocked} onChange={event => void update({ blocked: event.target.checked })} /> Blocked</label></div>
    <div className="detail-section"><div className="section-title"><h2>Checklist</h2><span>{task.checklist.filter(item => item.completed).length}/{task.checklist.length}</span></div>{task.checklist.map(item => <div className="check-row" key={item.id}><input type="checkbox" checked={item.completed} onChange={event => void onMutate(() => kanbanService.updateChecklistItem(task.id, item.id, { completed: event.target.checked }))} /><span className={item.completed ? 'completed' : ''}>{item.text}</span><button aria-label={`Delete ${item.text}`} onClick={() => void onMutate(() => kanbanService.deleteChecklistItem(task.id, item.id))}>×</button></div>)}<form className="inline-form" onSubmit={event => { event.preventDefault(); if (checkText.trim()) { void onMutate(() => kanbanService.addChecklistItem(task.id, checkText), 'Checklist item added'); setCheckText('') } }}><input aria-label="New checklist item" placeholder="Add an item…" value={checkText} onChange={event => setCheckText(event.target.value)} /><button>Add</button></form></div>
    <div className="detail-section"><div className="section-title"><h2>Discussion</h2><span>{task.comments.length}</span></div>{task.comments.map(item => <div className="comment" key={item.id}><span className="avatar tiny" style={{ background: snapshot.users[item.authorId].color }}>{snapshot.users[item.authorId].initials}</span><div><strong>{snapshot.users[item.authorId].name}</strong><p>{item.body}</p><div className="reactions">{['👍', '❤️', '🎉', '👀'].map(reaction => <button key={reaction} className={item.reactions[reaction]?.includes(snapshot.team.currentUserId) ? 'reaction selected' : 'reaction'} onClick={() => void onMutate(() => kanbanService.toggleReaction(task.id, item.id, reaction))}>{reaction} {item.reactions[reaction]?.length || ''}</button>)}</div></div></div>)}<form className="comment-form" onSubmit={event => { event.preventDefault(); if (comment.trim()) { void onMutate(() => kanbanService.addComment(task.id, comment), 'Comment added'); setComment('') } }}><input aria-label="Write a comment" placeholder="Write a comment… try @Noah" value={comment} onChange={event => setComment(event.target.value)} /><button>Post</button></form></div>
    <div className="dialog-footer"><button className="danger-button" onClick={async () => { if (window.confirm('Delete this task?')) { await onMutate(() => kanbanService.deleteTask(task.id), 'Task deleted'); onClose() } }}>Delete task</button><button className="secondary-button" onClick={async () => { await onMutate(() => task.archived ? kanbanService.restoreTask(task.id) : kanbanService.archiveTask(task.id), task.archived ? 'Task restored' : 'Task archived'); onClose() }}>{task.archived ? 'Restore task' : 'Archive task'}</button></div>
  </section></div>
}

function InfoPage({ page, onBack }: { page: Page; onBack: () => void }) {
  const about = page === 'about'
  return <section className="info-page"><button className="back-link" onClick={onBack}>← Back to workspace</button><div className="info-hero"><p className="eyebrow">{about ? 'A LITTLE ABOUT ORBIT' : 'ANSWERS, WITHOUT THE RUNAROUND'}</p><h1>{about ? 'Make space for better work.' : 'Frequently asked questions.'}</h1><p className="hero-copy">{about ? 'Orbit is a small, thoughtful kanban for teams who want clarity without a sea of settings. This interactive demo is a safe place to explore the flow.' : 'Everything you need to know about this demo workspace and the lightweight workflow behind it.'}</p></div><div className="info-cards">{(about ? [['What is this?', 'A front-end demo of a modern mini kanban board, seeded with realistic sample data so you can click around immediately.'], ['What can I try?', 'Create, move, edit, filter, archive, and delete tasks. Open a task to explore checklists, comments, reactions, and activity.'], ['What happens to my changes?', 'Changes stay in this browser during the demo. Use Reset demo in the sidebar whenever you want a clean start.']] : [['Is this connected to a backend?', 'No. The initial experience uses a mock service and browser persistence. It is designed so a real service can be connected later.'], ['What are the roles?', 'The seeded workspace has one Owner and several Members. The Owner can manage boards and invitations; everyone can work with tasks.'], ['What is intentionally excluded?', 'Authentication, real email, file uploads, external notifications, advanced permissions, and cross-user synchronization are outside this MVP.']]).map(([title, body]) => <article className="info-card" key={title}><span className="info-number">0{(about ? [['What is this?'], ['What can I try?'], ['What happens to my changes?']] : [['Is this connected to a backend?'], ['What are the roles?'], ['What is intentionally excluded?']]).findIndex(item => item[0] === title) + 1}</span><h2>{title}</h2><p>{body}</p></article>)}</div></section>
}
